export const fileNames = [
  "1c.svg",
  "1d.svg",
  "1h.svg",
  "1s.svg",
  "2c.svg",
  "2d.svg",
  "2h.svg",
  "2s.svg",
  "3c.svg",
  "3d.svg",
  "3h.svg",
  "3s.svg",
  "4c.svg",
  "4d.svg",
  "4h.svg",
  "4s.svg",
  "5c.svg",
  "5d.svg",
  "5h.svg",
  "5s.svg",
  "6c.svg",
  "6d.svg",
  "6h.svg",
  "6s.svg",
  "7c.svg",
  "7d.svg",
  "7h.svg",
  "7s.svg",
  "8c.svg",
  "8d.svg",
  "8h.svg",
  "8s.svg",
  "9c.svg",
  "9d.svg",
  "9h.svg",
  "9s.svg",
  "10c.svg",
  "10d.svg",
  "10h.svg",
  "10s.svg",
  "11c.svg",
  "11d.svg",
  "11h.svg",
  "11s.svg",
  "12c.svg",
  "12d.svg",
  "12h.svg",
  "12s.svg",
  "13c.svg",
  "13d.svg",
  "13h.svg",
  "13s.svg",
];

export const arrayOfSources = [
  "/static/media/1c.svg",
  "/static/media/1d.svg",
  "/static/media/1h.svg",
  "/static/media/1s.svg",
  "/static/media/2c.svg",
  "/static/media/2d.svg",
  "/static/media/2h.svg",
  "/static/media/2s.svg",
  "/static/media/3c.svg",
  "/static/media/3d.svg",
  "/static/media/3h.svg",
  "/static/media/3s.svg",
  "/static/media/4c.svg",
  "/static/media/4d.svg",
  "/static/media/4h.svg",
  "/static/media/4s.svg",
  "/static/media/5c.svg",
  "/static/media/5d.svg",
  "/static/media/5h.svg",
  "/static/media/5s.svg",
  "/static/media/6c.svg",
  "/static/media/6d.svg",
  "/static/media/6h.svg",
  "/static/media/6s.svg",
  "/static/media/7c.svg",
  "/static/media/7d.svg",
  "/static/media/7h.svg",
  "/static/media/7s.svg",
  "/static/media/8c.svg",
  "/static/media/8d.svg",
  "/static/media/8h.svg",
  "/static/media/8s.svg",
  "/static/media/9c.svg",
  "/static/media/9d.svg",
  "/static/media/9h.svg",
  "/static/media/9s.svg",
  "/static/media/10c.svg",
  "/static/media/10d.svg",
  "/static/media/10h.svg",
  "/static/media/10s.svg",
  "/static/media/11c.svg",
  "/static/media/11d.svg",
  "/static/media/11h.svg",
  "/static/media/11s.svg",
  "/static/media/12c.svg",
  "/static/media/12d.svg",
  "/static/media/12h.svg",
  "/static/media/12s.svg",
  "/static/media/13c.svg",
  "/static/media/13d.svg",
  "/static/media/13h.svg",
  "/static/media/13s.svg",
];

export async function cacheImages(arrayOfImageSources) {
  const promises = await arrayOfImageSources.map((src) => {
    /*     return new Promise((resolve, reject) => {
      const img = new Image();
      img.src = src;
      img.onload = resolve();
      img.onerror = reject();
    }); */
    return fetch(src);
  });

  // Wait for all promises to get done
  return await Promise.all(promises);
}
